dependencies:

compiler:
  solc:
    remappings:

dotenv: .env

wallets:
  dev_account_1: 
    address: ${D1_ADDRESS}
    private_key: ${D1_PRIVATE_KEY}

networks:

  kovan:
    local: False
    verify: True
    weth_address : '0xd0a1e359811322d97991e03f863a0c30c2cf029c'

  mainnet-fork:
    local: 'fork'
    verify: True
    weth_address : '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
